// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoxZLJNqeI3YMFa_ZblT_kMrrUiHTEtEQ',
    appId: '1:761806965762:web:d5f6e9489eb6a09bbf2b1b',
    messagingSenderId: '761806965762',
    projectId: 'instagram-app-2023',
    authDomain: 'instagram-app-2023.firebaseapp.com',
    storageBucket: 'instagram-app-2023.appspot.com',
    measurementId: 'G-8JP59GRTQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ev6q1u21w5YCKiJDEm3S3NeqyEJhmN8',
    appId: '1:761806965762:android:982f4dde06f73d55bf2b1b',
    messagingSenderId: '761806965762',
    projectId: 'instagram-app-2023',
    storageBucket: 'instagram-app-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdYeyg8BFXetY-GEFiF-LzZJBuWuGZ8AE',
    appId: '1:761806965762:ios:e5009deb6f3ec2f4bf2b1b',
    messagingSenderId: '761806965762',
    projectId: 'instagram-app-2023',
    storageBucket: 'instagram-app-2023.appspot.com',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdYeyg8BFXetY-GEFiF-LzZJBuWuGZ8AE',
    appId: '1:761806965762:ios:56553a0caf37764abf2b1b',
    messagingSenderId: '761806965762',
    projectId: 'instagram-app-2023',
    storageBucket: 'instagram-app-2023.appspot.com',
    iosBundleId: 'com.example.instagramApp.RunnerTests',
  );
}
